config_map:
  - name: JBOSS_A_MQ_BROKER_URL
    value: tcp://{{ microservice }}-amq-tcp.{{ project }}.svc:61616
  - name: COUCHBASE_HOST
    value: couchbase.{{ project }}.svc
  - name: COUCHBASE_BUCKET
    value: "{{ microservice }}-{{ project }}"
  - name: JAEGER_SERVICE_NAME
    value: build-{{ project }}
  - name: JAEGER_SAMPLER_TYPE
    value: const
  - name: JAEGER_SAMPLER_PARAM
    value: 1
  - name: JAEGER_SAMPLER_MANAGER_HOST_PORT
    value: jaeger-agent.blockchain-demo-monitoring.svc:5778    
  - name: JAEGER_AGENT_HOST
    value: jaeger-agent.blockchain-demo-monitoring.svc      